version: "3.3"
services:
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "80:80"
    networks:
      - proxy

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    #ports:
    #  - '3000:3000'
    volumes:
      - /app/node_modules
    restart: on-failure
    container_name: client
    networks:
      - proxy

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    #ports:
    #  - '8080:8080'
    restart: on-failure
    container_name: backend
    volumes:
      - /app/node_modules
    env_file:
      - ./env/backend.env
    networks:
      - proxy

networks:
  proxy:
    driver: bridge
